name: weather
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-26.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Logics
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  geolocator: ^10.1.0
  connectivity_plus: ^5.0.1
  equatable: ^2.0.5
  intl: ^0.18.1
  home_widget: ^0.3.0


  #UI
  animate_do: ^3.1.2
  dismissible_page: ^1.0.2
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  shimmer_animation: ^2.1.0+1
  awesome_notifications: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo-square.png"

flutter:
  uses-material-design: true

  assets:
   - assets/icons/
   - assets/images/
   - assets/weather_icons/day/
   - assets/weather_icons/night/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
